//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifier.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifier.Localization.Resources.en-us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string AlertForm_DiscardButton {
            get {
                return ResourceManager.GetString("AlertForm_DiscardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end of work day.
        /// </summary>
        internal static string AlertForm_EndOfWorkDayDescription {
            get {
                return ResourceManager.GetString("AlertForm_EndOfWorkDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of work day ({0}).
        /// </summary>
        internal static string AlertForm_EndOfWorkDayTitle {
            get {
                return ResourceManager.GetString("AlertForm_EndOfWorkDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s now the.
        /// </summary>
        internal static string AlertForm_ItsNowThe {
            get {
                return ResourceManager.GetString("AlertForm_ItsNowThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lunch time.
        /// </summary>
        internal static string AlertForm_LunchLeavingDescription {
            get {
                return ResourceManager.GetString("AlertForm_LunchLeavingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving for lunch ({0}).
        /// </summary>
        internal static string AlertForm_LunchLeavingTitle {
            get {
                return ResourceManager.GetString("AlertForm_LunchLeavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backing from lunch.
        /// </summary>
        internal static string AlertForm_LunchReturningDescription {
            get {
                return ResourceManager.GetString("AlertForm_LunchReturningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing from lunch ({0}).
        /// </summary>
        internal static string AlertForm_LunchReturningTitle {
            get {
                return ResourceManager.GetString("AlertForm_LunchReturningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute,2 minutes,3 minutes,4 minutes,5 minutes,6 minutes,7 minutes,8 minutes,9 minutes,10 minutes.
        /// </summary>
        internal static string AlertForm_MinutesList {
            get {
                return ResourceManager.GetString("AlertForm_MinutesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute left for the.
        /// </summary>
        internal static string AlertForm_MissingOneMinuteFor {
            get {
                return ResourceManager.GetString("AlertForm_MissingOneMinuteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes to.
        /// </summary>
        internal static string AlertForm_MissingXMinutesFor {
            get {
                return ResourceManager.GetString("AlertForm_MissingXMinutesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me again in.
        /// </summary>
        internal static string AlertForm_PostponeButton {
            get {
                return ResourceManager.GetString("AlertForm_PostponeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re one minute late for the.
        /// </summary>
        internal static string AlertForm_YouAreOneMinuteLateFor {
            get {
                return ResourceManager.GetString("AlertForm_YouAreOneMinuteLateFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re {0} minutes late for the.
        /// </summary>
        internal static string AlertForm_YouAreXMinutesLateFor {
            get {
                return ResourceManager.GetString("AlertForm_YouAreXMinutesLateFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse image.
        /// </summary>
        internal static string Config_Browse_Image {
            get {
                return ResourceManager.GetString("Config_Browse_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse sound.
        /// </summary>
        internal static string Config_Browse_Sound {
            get {
                return ResourceManager.GetString("Config_Browse_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must be reinitialized to assume new language configuration..
        /// </summary>
        internal static string Config_ChangeLanguageMessage {
            get {
                return ResourceManager.GetString("Config_ChangeLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Config_ComboItem_Custom {
            get {
                return ResourceManager.GetString("Config_ComboItem_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Config_ComboItem_Default {
            get {
                return ResourceManager.GetString("Config_ComboItem_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Config_ComboItem_None {
            get {
                return ResourceManager.GetString("Config_ComboItem_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ({0}).
        /// </summary>
        internal static string Config_Custom {
            get {
                return ResourceManager.GetString("Config_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ({0}).
        /// </summary>
        internal static string Config_Custom_Image {
            get {
                return ResourceManager.GetString("Config_Custom_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ({0}).
        /// </summary>
        internal static string Config_Custom_Sound {
            get {
                return ResourceManager.GetString("Config_Custom_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Config_EndOfWorkDay_Color {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom image for the end of work day..
        /// </summary>
        internal static string Config_EndOfWorkDay_MessageForMissingImage {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_MessageForMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom sound for the end of work day..
        /// </summary>
        internal static string Config_EndOfWorkDay_MessageForMissingSound {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_MessageForMissingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test alert.
        /// </summary>
        internal static string Config_EndOfWorkDay_TestAlert {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_TestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total working time.
        /// </summary>
        internal static string Config_EndOfWorkDay_Time {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me at the end of work day.
        /// </summary>
        internal static string Config_EndOfWorkDay_Title {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Config_EndOfWorkDay_WarnImage {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_WarnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me.
        /// </summary>
        internal static string Config_EndOfWorkDay_WarnMe {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_WarnMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s) before.
        /// </summary>
        internal static string Config_EndOfWorkDay_WarnMeAfter {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_WarnMeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound alert.
        /// </summary>
        internal static string Config_EndOfWorkDay_WarnSound {
            get {
                return ResourceManager.GetString("Config_EndOfWorkDay_WarnSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.jpg, *.png, *.gif).
        /// </summary>
        internal static string Config_File_Types_Image {
            get {
                return ResourceManager.GetString("Config_File_Types_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound files (*.wav).
        /// </summary>
        internal static string Config_File_Types_Sound {
            get {
                return ResourceManager.GetString("Config_File_Types_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Config_FormTitle {
            get {
                return ResourceManager.GetString("Config_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Config_General {
            get {
                return ResourceManager.GetString("Config_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Config_Language {
            get {
                return ResourceManager.GetString("Config_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Config_LunchLeaving_Color {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom image for the lunch leaving..
        /// </summary>
        internal static string Config_LunchLeaving_MessageForMissingImage {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_MessageForMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom sound for the lunch leaving..
        /// </summary>
        internal static string Config_LunchLeaving_MessageForMissingSound {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_MessageForMissingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test alert.
        /// </summary>
        internal static string Config_LunchLeaving_TestAlert {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_TestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Config_LunchLeaving_Time {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me at lunch leaving.
        /// </summary>
        internal static string Config_LunchLeaving_Title {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Config_LunchLeaving_WarnImage {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_WarnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me.
        /// </summary>
        internal static string Config_LunchLeaving_WarnMe {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_WarnMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s) before.
        /// </summary>
        internal static string Config_LunchLeaving_WarnMeAfter {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_WarnMeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound alert.
        /// </summary>
        internal static string Config_LunchLeaving_WarnSound {
            get {
                return ResourceManager.GetString("Config_LunchLeaving_WarnSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Config_LunchReturning_Color {
            get {
                return ResourceManager.GetString("Config_LunchReturning_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom image for the lunch returning..
        /// </summary>
        internal static string Config_LunchReturning_MessageForMissingImage {
            get {
                return ResourceManager.GetString("Config_LunchReturning_MessageForMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the custom sound for the lunch returning..
        /// </summary>
        internal static string Config_LunchReturning_MessageForMissingSound {
            get {
                return ResourceManager.GetString("Config_LunchReturning_MessageForMissingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test alert.
        /// </summary>
        internal static string Config_LunchReturning_TestAlert {
            get {
                return ResourceManager.GetString("Config_LunchReturning_TestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Config_LunchReturning_Time {
            get {
                return ResourceManager.GetString("Config_LunchReturning_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me at lunch returning.
        /// </summary>
        internal static string Config_LunchReturning_Title {
            get {
                return ResourceManager.GetString("Config_LunchReturning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Config_LunchReturning_WarnImage {
            get {
                return ResourceManager.GetString("Config_LunchReturning_WarnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn me.
        /// </summary>
        internal static string Config_LunchReturning_WarnMe {
            get {
                return ResourceManager.GetString("Config_LunchReturning_WarnMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s) before.
        /// </summary>
        internal static string Config_LunchReturning_WarnMeAfter {
            get {
                return ResourceManager.GetString("Config_LunchReturning_WarnMeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound alert.
        /// </summary>
        internal static string Config_LunchReturning_WarnSound {
            get {
                return ResourceManager.GetString("Config_LunchReturning_WarnSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick color.
        /// </summary>
        internal static string Config_Select_Color {
            get {
                return ResourceManager.GetString("Config_Select_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse file.
        /// </summary>
        internal static string Config_SelectFile_FileSystem {
            get {
                return ResourceManager.GetString("Config_SelectFile_FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif searcher.
        /// </summary>
        internal static string Config_SelectFile_GifSearcher {
            get {
                return ResourceManager.GetString("Config_SelectFile_GifSearcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string Config_StartWithWindows {
            get {
                return ResourceManager.GetString("Config_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test alert.
        /// </summary>
        internal static string Config_Test_Alert {
            get {
                return ResourceManager.GetString("Config_Test_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test sound.
        /// </summary>
        internal static string Config_Test_Sound {
            get {
                return ResourceManager.GetString("Config_Test_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use animation to show alerts.
        /// </summary>
        internal static string Config_UseAnimation {
            get {
                return ResourceManager.GetString("Config_UseAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image.
        /// </summary>
        internal static string Config_View_Image {
            get {
                return ResourceManager.GetString("Config_View_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifier.
        /// </summary>
        internal static string General_AppName {
            get {
                return ResourceManager.GetString("General_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string General_Attention {
            get {
                return ResourceManager.GetString("General_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is english.
        /// </summary>
        internal static string General_Test {
            get {
                return ResourceManager.GetString("General_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch more.
        /// </summary>
        internal static string ImageSearch_FetchMore {
            get {
                return ResourceManager.GetString("ImageSearch_FetchMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image searcher.
        /// </summary>
        internal static string ImageSearch_FormTitle {
            get {
                return ResourceManager.GetString("ImageSearch_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        internal static string ImageSearch_GetTrending {
            get {
                return ResourceManager.GetString("ImageSearch_GetTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ImageSearch_Search {
            get {
                return ResourceManager.GetString("ImageSearch_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} image(s) found. Showing from {1} to {2}.
        /// </summary>
        internal static string ImageSearch_Status {
            get {
                return ResourceManager.GetString("ImageSearch_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform a valid time.
        /// </summary>
        internal static string SetEntrance_Alert_InformValidTime {
            get {
                return ResourceManager.GetString("SetEntrance_Alert_InformValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must leave at {0}.
        /// </summary>
        internal static string SetEntrance_Alert_YouShouldLeaveAt {
            get {
                return ResourceManager.GetString("SetEntrance_Alert_YouShouldLeaveAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry time.
        /// </summary>
        internal static string SetEntrance_FormTitle {
            get {
                return ResourceManager.GetString("SetEntrance_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SetEntrance_SetButton {
            get {
                return ResourceManager.GetString("SetEntrance_SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify entry time ({0}).
        /// </summary>
        internal static string Tray_ChangeEntranceTime {
            get {
                return ResourceManager.GetString("Tray_ChangeEntranceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to inform entry time..
        /// </summary>
        internal static string Tray_ClickToInformArrivingTime {
            get {
                return ResourceManager.GetString("Tray_ClickToInformArrivingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event logger.
        /// </summary>
        internal static string Tray_EventLogger {
            get {
                return ResourceManager.GetString("Tray_EventLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform entry time.
        /// </summary>
        internal static string Tray_InformEntranceTime {
            get {
                return ResourceManager.GetString("Tray_InformEntranceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
    }
}
